name: cd

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_runner:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: extractions/setup-just@v1
      - name: Docker build
        run: just build
      - name: Docker Push
        run: just push
